### PR TITLE
.github/workflows: run add chain test

### PR DESCRIPTION
**Pull request by makramkd**
Run the `TestAddChainInbound` test from the ccip deployment package so that we ensure that our discovery processor is working as expected.

### CODE REVIEW

**Review by asoliman92 — COMMENTED** [review]
Can't we just run all ccip tests under deployment instead of adding one by one?

**Comment by makramkd** [comment]
Also, there is a non-trivial subset of the tests that are not really relevant to this codebase.

**Comment by dimkouv** [comment]
If it makes sense we can de-dup this
```
func run_integ_test(test_name)
          cd $GITHUB_WORKSPACE/chainlink/integration-tests
          go test ... $test_name ...
          EXITCODE=${PIPESTATUS[0]}
          if [ $EXITCODE -ne 0 ]; then
            echo "Integration test failed"
          else
            echo "Integration test passed!"
          fi
          exit $EXITCODE
        env:
          CL_DATABASE_URL: ${{ env.DB_URL }}
```

**Comment by makramkd** [comment]
Are there functions in yaml? 😛

**Comment by dimkouv** [comment]
No, but I think the preferred approach is to have a `scripts/` dir and use bash.

**Pull request merged**
